sudo: required
dist: trusty
services:
  - docker
  - mysql
language: scala
scala:
  - 2.12.6
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    # see cromwell::private::delete_sbt_boot for more info
    #- $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.coursier/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete
env:
  matrix:
    # Setting this variable twice will cause the 'script' section to run twice with the respective env var invoked
    - BUILD_TYPE=centaurAws
    - BUILD_TYPE=centaurBcs
    - BUILD_TYPE=centaurEngineUpgradeLocal
    - BUILD_TYPE=centaurEngineUpgradePapiV2
    - BUILD_TYPE=centaurPapiUpgradePapiV1
    - BUILD_TYPE=centaurPapiUpgradeNewWorkflowsPapiV1
    - BUILD_TYPE=centaurLocal
    - BUILD_TYPE=centaurPapiV1
    - BUILD_TYPE=centaurPapiV2
    - BUILD_TYPE=centaurTes
    - BUILD_TYPE=centaurWdlUpgradeLocal
    - BUILD_TYPE=checkPublish
    - BUILD_TYPE=conformanceLocal
    - BUILD_TYPE=conformancePapiV2
    - BUILD_TYPE=conformanceTesk
    - BUILD_TYPE=dockerDeadlock
    - BUILD_TYPE=dockerScripts
    - BUILD_TYPE=sbt
  global:
    # This is the variable `VAULT_TOKEN_GIT_COMMITTED`.
    #
    # WARNING: THIS ACCESS TOKEN WILL EXPIRE TOWARDS THE THIRD WEEK OF FEB `19.
    #
    # Hopefully https://support.travis-ci.com/hc/en-us/requests/3231 is resolved by then and we can
    # go back to using variables set in the Travis Repository Settings.
    secure: "lVQOcEcSHDu3GAzg4QqjxTTJHZs5W4waTHFOVqq20+D8T+r0vNuiNciicB0zqxPtoOLFRPqoEAKnbtDzOpRqPdGKu4HVyFPf8FFVRh1VINp35PH25ScUYk8TXmd5xFhoDpKzFV3QT1zSKR7Cv5Pd5qkvAoL2KXLMCCmxd3p8F0A="
script:
  - src/ci/bin/test.sh
notifications:
  slack:
    rooms:
      - secure: B5KYcnhk/ujAUWlHsjzP7ROLm6MtYhaGikdYf6JYINovhMbVKnZCTlZEy7rqT3L2T5uJ25iefD500VQGk1Gn7puQ1sNq50wqjzQaj20PWEiBwoWalcV/nKBcQx1TyFT13LJv8fbFnVPxFCkC3YXoHedx8qAhDs8GH/tT5J8XOC8=
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
    on_success: change
    on_failure: change
    on_pull_requests: false
